### ISSUE TITLE
how do you use the getCode() method?

### ISSUE THREAD

**Issue by shikiko** [PaulMiami/Authenticator#2]
i am trying to get the totp code to use to verify it when the user inputs from their phone. how do you do this?

**Comment by PaulMiami** [comment]
Hi,

You can check out the sample code for [GetCode()](https://github.com/PaulMiami/Authenticator/blob/develop/sample/TestWebApp/Controllers/AuthenticatorController.cs#L23) and the corresponding [GetUri()](https://github.com/PaulMiami/Authenticator/blob/develop/sample/TestWebApp/Controllers/HomeController.cs#L40)
Also see the [unit test](https://github.com/PaulMiami/Authenticator/blob/develop/test/Authentication.Authenticator.Test/AuthenticatorServiceTest.cs#L146)
 
The basics is to generate the "otpauth" Uri and input it into your phone app (render it as [qrcode](https://github.com/PaulMiami/Authenticator/blob/develop/sample/TestWebApp/Views/Home/Index.cshtml#L40)) and call GetCode() with the same parameters use to generate the Uri to get the next code.
